force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>DATEVALUE( $System.OriginDateTime)</defaultValue>
    <description>Date of the Race</description>
    <inlineHelpText>Date of the Race</inlineHelpText>
    <label>Date of the Race</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current Race status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PostponeRaceBatch.cls
public class PostponeRaceBatch implements Database.Batchable<sObject>, Database.Stateful {
  public List<String> racesID = new List<String>();

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      [SELECT id, Date__c FROM Race__c WHERE Status__c = 'Active']
    );
  }

  public void execute(Database.BatchableContext cd, List<Race__c> scope) {
    for (Race__c race : scope) {
      race.Date__c = race.Date__c.addMonths(1);
      racesID.add(race.id);
    }

    update scope;
  }

  public void finish(Database.BatchableContext bc) {
    String body =
      'PostponeRaceBatch is Done job. List Race Ids: ' +
      String.join(racesID, ',');

    Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
    String[] sendingTo = new List<String>{ 'nrg.xiii@gmail.com' };
    semail.setToAddresses(sendingTo);
    semail.setSubject('PostponeRaceBatch');
    semail.setPlainTextBody(body);
    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ semail });

    System.debug(body);
  }
}