force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Race Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Racing Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FormulaOneServices.cls
public class FormulaOneServices {
    public static String generateKey (SObject record, List<SObjectField> fields, String separator){

        List<String> stringFields = new List<String>();
		stringFields.add(
            record.get(fields)
        );
        string key;
        for(String s: stringFields){
            Key = Key + separator + s;
        }
        
        return Key; 
    }
    
    public static Boolean isHatTrick(Race_Result__c raceResult){
        if (raceResult.Position__c == 1 && raceResult.Grid__c == 1 && raceResult.Is_Fastest_Lap__c)
        {
            return true;
                } 
        else 
        {
            return false;
                }       
    }
}