force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.)</description>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver(Full years)</description>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Full Name of the driver</description>
    <formula>Last_Name__c  &amp; &quot;, &quot; &amp;  First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Hat_Tricks__c.field-meta.xml
<CustomField>
    <fullName>Hat_Tricks__c</fullName>
    <description>Total amount of won Races finished with the fastest lap and took 1st place</description>
    <label>Hat Tricks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Is_Qualified__c.field-meta.xml
<CustomField>
    <fullName>Is_Qualified__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is Driver qualified or not</description>
    <label>Is Qualified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver</description>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Race Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Racing Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Racing Results</relationshipLabel>
    <relationshipName>Racing_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Driver attended the Race</description>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Racing Results</relationshipLabel>
    <relationshipName>Racing_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormulaOneDAO.cls
public with sharing class FormulaOneDAO {
    // test driverid = a027Q0000061zcxQAA for Hadgehoc, Sonic
    public static Driver__c getDriver(Id driverId){
        return [SELECT Age__c, CreatedById, Name, First_Name__c, Full_Name__c, Hat_Tricks__c, Is_Qualified__c, LastModifiedById, Last_Name__c, OwnerId FROM Driver__c WHERE Id = :driverId];
    }
    

    public static List<Race_Result__c> getRaceResults(Id driverId){
         return [SELECT CreatedById, Grand_Prix__c, Grid__c, Is_Fastest_Lap__c, LastModifiedById, Position__c, Name, Racer__c FROM Race_Result__c where Racer__c = :driverId];
    }

    
    public static set<String> getDriverCircuits(Id driverId){
 		List<Race_Result__c> qResults = [SELECT Grand_Prix__r.Name FROM Race_Result__c WHERE Racer__c = :driverId];
        Set<String> resultNamesSet = new Set<String>();
        
        for (Race_Result__c r: qResults) {
            resultNamesSet.add(r.Grand_Prix__r.Name);
        }

        return resultNamesSet;

    }
     
    public static Driver__c getYoungestDriverOnRace(Id raceId){
        return [SELECT Name, Age__C FROM Driver__c  
                WHERE Id IN 
               (SELECT Racer__c FROM Race_Result__c 
                WHERE Grand_Prix__c = :raceId) 
                ORDER BY Age__c LIMIT 1];
    }
    
   
    public static Map<String, List<String>> getAllDriversByCircuit(){
        Map<String, list<String>> AllDriversByCircuit = new Map<String, list<String>>();
        List<Race_Result__c> raceRezList =[SELECT Grand_Prix__r.Name, Racer__r.Name FROM Race_Result__c];
        
        For(Race_Result__c tempRaceRez: raceRezList){
            if(AllDriversByCircuit.containsKey(tempRaceRez.Grand_Prix__r.Name)){
                AllDriversByCircuit.get(tempRaceRez.Grand_Prix__r.Name).add(tempRaceRez.Racer__r.Name);
            } else {
                AllDriversByCircuit.put(tempRaceRez.Grand_Prix__r.Name, new List<String>{tempRaceRez.Racer__r.Name});
            }
        }
       
        return AllDriversByCircuit;
    }
    /* Old version
   public Map<String, List<String>> getAllDriversByCircuit(){
        Map<String, list<String>> AllDriversByCircuit = new Map<String, list<String>>();
        List<sObject> raceRezList = new List<sObject>{
            Database.query('SELECT Grand_Prix__r.Name, Racer__r.Name FROM Race_Result__c ORDER BY Grand_Prix__r.Name')
                };
        
        String oldRaceName = String.valueOf(raceRezList[0].get('Grand_Prix__r.Name'));
		String newRaceName = oldRaceName;
		List<String> curRaceDrivers = new List<String>();
        For(sObject tempRaceRez: raceRezList){

			
            if(oldRaceName == newRaceName){
                curRaceDrivers.add(String.valueOf(tempRaceRez.get('Racer__r.Name')));
            } else {
                AllDriversByCircuit.put(oldRaceName, curRaceDrivers);
				oldRaceName = newRaceName;
				curRaceDrivers.clear();
                curRaceDrivers.add(String.valueOf(tempRaceRez.get('Racer__r.Name')));
            }
            newRaceName = String.valueOf(tempRaceRez.get('Grand_Prix__r.Name'));
        }
        
        AllDriversByCircuit.put(oldRaceName, curRaceDrivers);
        return AllDriversByCircuit;
    }*/

}