force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.)</description>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver(Full years)</description>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver</description>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>DATEVALUE( $System.OriginDateTime)</defaultValue>
    <description>Date of the Race</description>
    <inlineHelpText>Date of the Race</inlineHelpText>
    <label>Date of the Race</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Laps__c.field-meta.xml
<CustomField>
    <fullName>Laps__c</fullName>
    <description>Number of Laps</description>
    <label>Laps</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current Race status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Race__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <description>Race Track</description>
    <inlineHelpText>current track</inlineHelpText>
    <label>Track</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVUS</fullName>
                <default>true</default>
                <label>AVUS</label>
            </value>
            <value>
                <fullName>Circuit de Monaco</fullName>
            </value>
            <value>
                <fullName>Mosport Park</fullName>
            </value>
            <value>
                <fullName>Nurburgring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Race Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Racing Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Racing Results</relationshipLabel>
    <relationshipName>Racing_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Driver attended the Race</description>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Racing Results</relationshipLabel>
    <relationshipName>Racing_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormulaOneServicesTest.cls
@isTest 
private class FormulaOneServicesTest {

@TestSetup
    static void dataSetup(){
      //  TestDataFactory.createTestData();
          
      List<Race__c> racesList = new List<Race__c>();
      List<Driver__c> driversList = new List<Driver__c>();
  
      for (Integer i = 0; i==6; i++) {
          driversList.add(new Driver__c(
              First_Name__c = 'First_name_' + i,
              Last_Name__c = 'Last_name_' + i,
              Age__c = i + 17
          ));
      }       
   
      racesList.add(new Race__c(        
          Name = 'Grond_prix_name_1',
          Track__c = 'AVUS',
          Date__c = Date.newInstance(2022, 10, 19),
          Laps__c  =  3,
          Status__c = 'Active'
      ));
      racesList.add(new Race__c(        
          Name = 'Grond_prix_name_2',
          Track__c = 'Circuit de Monaco',
          Date__c = Date.newInstance(2022, 01, 05),
          Laps__c  =  5,
          Status__c = 'Completed'
      ));
      racesList.add(new Race__c(        
          Name = 'Grond_prix_name_3',
          Track__c = 'Mosport Park', 
          Date__c = Date.newInstance(2023, 06, 03),
          Laps__c  =  7,
          Status__c = 'Active'
      ));
      racesList.add(new Race__c(        
          Name = 'Grond_prix_name_4',
          Track__c = 'Nurburgring',
          Date__c = Date.newInstance(2099, 01, 01),
          Laps__c  =  1 ,
          Status__c =  'Completed'
      ));
          
      insert driversList;
      insert racesList;


        
      List<Id> drvsId = new List<Id>(new Map<Id, Driver__c>([SELECT id FROM Driver__c]).keySet());
 	  List<Id> rcsId = new List<Id>(new Map<Id, Race__c>([SELECT id FROM Race__c]).keySet());
     
      List<Race_Result__c> raceResultsList = new List<Race_Result__c>();

      For(Id r: rcsId){
          integer driverPosition = 1;
          Boolean fastestLap = true;
          for (id d : drvsId) {
              raceResultsList.add(new Race_Result__c(
                  Grand_Prix__c = r,
                  Grid__c = driverPosition,                    
                  Is_Fastest_Lap__c = fastestLap,
                  Position__c = driverPosition,
                  // Name = String.valueOf(d + '_' + driverPosition),
                  Racer__c = d
              ));
              fastestLap = false;
              driverPosition++;
          }
      }
      insert raceResultsList;
    }

@isTest 
    static void generateKeyTest() {
        //sObject testsObj = new sObject();
        Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        String objectName='Race__c';
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get(ObjectName).getDescribe().fields.getMap();

        List<sObjectField> testFieldsList = new list<SObjectField>();
        testFieldsList.add(fieldMap.get('Name'));
        testFieldsList.add(fieldMap.get('Track__c'));
        
        Race__c testsObj = [SELECT Name,Track__c FROM Race__c LIMIT 1];

        string expectedResult = 'Grond_prix_name_1---AVUS';

        Test.startTest();
            String testResult = FormulaOneServices.generateKey(testsObj, testFieldsList, '---');
        Test.stopTest();

        System.assertEquals(expectedResult, testResult, 'FormulaOneServices.generateKey TEST FAILURE');
    }

    @isTest
    static void isHatTrickTest(){
        List<Race_Result__c> raceResultRecords = [SELECT Position__c, Grid__c, Is_Fastest_Lap__c FROM Race_Result__c LIMIT 2];
      //  System.debug(records[1] + records[2]);
       /* Race_Result__c correctRaceResult = new Race_Result__c(
            Position__c = 1, Grid__c = 1, Is_Fastest_Lap__c = true);
        Race_Result__c correctRaceResult = new Race_Result__c(
            Position__c = 2, Grid__c = 2, Is_Fastest_Lap__c = false);*/

        Test.startTest();
        Boolean resultTrue = FormulaOneServices.isHatTrick(records.get(0));
        Boolean resultFalse = FormulaOneServices.isHatTrick(records.get(1));
        Test.stopTest();

        System.assertEquals(true, resultTrue, 'FormulaOneServices.isHatTrickTest TEST FAILURE');
        System.assertEquals(false, resultFalse, 'FormulaOneServices.isHatTrickTest NEGATIVE TEST FAILURE');

    }

}