force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.)</description>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver(Full years)</description>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Hat_Tricks__c.field-meta.xml
<CustomField>
    <fullName>Hat_Tricks__c</fullName>
    <description>Total amount of won Races finished with the fastest lap and took 1st place</description>
    <label>Hat Tricks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Is_Qualified__c.field-meta.xml
<CustomField>
    <fullName>Is_Qualified__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is Driver qualified or not</description>
    <label>Is Qualified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver</description>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>DATEVALUE( $System.OriginDateTime)</defaultValue>
    <description>Date of the Race</description>
    <inlineHelpText>Date of the Race</inlineHelpText>
    <label>Date of the Race</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Laps__c.field-meta.xml
<CustomField>
    <fullName>Laps__c</fullName>
    <description>Number of Laps</description>
    <label>Laps</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current Race status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Race__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <description>Race Track</description>
    <inlineHelpText>current track</inlineHelpText>
    <label>Track</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVUS</fullName>
                <default>true</default>
                <label>AVUS</label>
            </value>
            <value>
                <fullName>Circuit de Monaco</fullName>
            </value>
            <value>
                <fullName>Mosport Park</fullName>
            </value>
            <value>
                <fullName>Nurburgring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Race Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Racing Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Racing Results</relationshipLabel>
    <relationshipName>Racing_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Driver attended the Race</description>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Racing Results</relationshipLabel>
    <relationshipName>Racing_Results</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/raceResultTriggerHandlerTest.cls
@isTest
private class raceResultTriggerHandlerTest{
    @testSetup
    static void dataSetup(){     
        
      List<Driver__c> driversList = new List<Driver__c>();
     /* for (Integer i = 0; i==6; i++) {
          driversList.add(new Driver__c(
              First_Name__c = 'Test_' + i,
              Last_Name__c = 'Driver_' + i,
              Age__c = i + 19
          ));
      }  */
      driversList.add(new Driver__c(
          First_Name__c = 'Test_1',
          Last_Name__c = 'Driver_1',
          Age__c =  20,
          Hat_Tricks__c = 0,
          Is_Qualified__c = True));
     driversList.add(new Driver__c(
          First_Name__c = 'Test_2',
          Last_Name__c = 'Driver_2',
          Age__c =  19,
          Hat_Tricks__c = 0,
          Is_Qualified__c = True));
     driversList.add(new Driver__c(
          First_Name__c = 'Test_3',
          Last_Name__c = 'Driver_3',
          Age__c =  35,
          Hat_Tricks__c = 0,
          Is_Qualified__c = True));
    driversList.add(new Driver__c(
          First_Name__c = 'Test_4',
          Last_Name__c = 'Driver_4',
          Age__c =  33,
          Hat_Tricks__c = 0,
          Is_Qualified__c = True));
/*    driversList.add(new Driver__c(
          First_Name__c = 'Test_5',
          Last_Name__c = 'Driver_5',
          Age__c =  23,
          Hat_Tricks__c = 0,
          Is_Qualified__c = True));
    driversList.add(new Driver__c(
          First_Name__c = 'Test_6',
          Last_Name__c = 'Driver_6',
          Age__c =  22,
          Hat_Tricks__c = 0,
          Is_Qualified__c = True));*/
      insert driversList;
        
      List<Race__c> racesList = new List<Race__c>();
      racesList.add(new Race__c(        
          Name = 'Grond_prix_name_1',
          Track__c = 'AVUS',
          Date__c = Date.newInstance(2022, 10, 19),
          Laps__c  =  3,
          Status__c = 'Active'));
     
      insert racesList;
        
      List<Id> drvsId = new List<Id>(new Map<Id, Driver__c>([SELECT id FROM Driver__c OFFSET 1]).keySet());
      List<Id> rcsId = new List<Id>(new Map<Id, Race__c>([SELECT id FROM Race__c]).keySet());
     
      List<Race_Result__c> raceResultsList = new List<Race_Result__c>();
      For(Id r: rcsId){
          if(r != NULL){
              integer driverPosition = 2;
              Boolean fastestLap = false;
              for (id d : drvsId) {
                  raceResultsList.add(new Race_Result__c(
                      Grand_Prix__c = r,
                      Grid__c = driverPosition,                    
                      Is_Fastest_Lap__c = fastestLap,
                      Position__c = driverPosition,
                      // Name = String.valueOf(d + '_' + driverPosition),
                      Racer__c = d
                  ));
                  
                  System.debug('Race-(' + r + ') Position-' + driverPosition + ' Driver-[' + d + ']');
                  fastestLap = false;
                  driverPosition++;
              }
          }
      }
    System.debug(raceResultsList);
      insert raceResultsList;

 
      insert new Driver__c(
        First_Name__c = 'Test_HatTricks',
        Last_Name__c = 'Driver',
        Age__c =  22,
        Hat_Tricks__c = 0,
        Is_Qualified__c = True);
      
    }
    
    @isTest
    static void driverHatTricksUpd(){
        Race__c race = [SELECT id FROM Race__c LIMIT 1];
        id raceId = race.id;
        Driver__c driver = [SELECT id FROM Driver__c WHERE First_Name__c = 'Test_HatTricks' LIMIT 1];
        Id driverId = driver.Id;

        Driver__c oldDriver = [SELECT id, Hat_Tricks__c FROM Driver__c WHERE id = :driverId];
        Decimal oldHatTricks = oldDriver.Hat_Tricks__c;

        Race_Result__c insertRaceResult = new Race_Result__c(
            Racer__c = driverId,
            Grand_Prix__c = raceId,
            Position__c = 1,
            Is_Fastest_Lap__c = true
        );
        Test.startTest();
        Upsert insertRaceResult;
        Test.stopTest();

        Decimal expectedHatTricks = oldHatTricks + 1;
        Driver__c newDriver = [SELECT id, Hat_Tricks__c FROM Driver__c WHERE id = :driverId];
        Decimal actualHatTricks = newDriver.Hat_Tricks__c;

        System.assertEquals(expectedHatTricks, actualHatTricks, 
        					'raceResultTriggerHandlerTest.driverHatTricksUpd Hat_Tricks__c TEST FAILURE');

    }
    
    @isTest
    static void driverPositionCheck(){
    
    }
    
}